export const JOB_TITLES = [
  // Software Engineering & Development
  'Software Engineer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Mobile Developer',
  'iOS Developer',
  'Android Developer',
  'DevOps Engineer',
  'Site Reliability Engineer',
  'Cloud Engineer',
  'Security Engineer',
  'QA Engineer',
  'Test Engineer',
  'Automation Engineer',
  'Systems Engineer',
  'Network Engineer',
  'Database Administrator',
  'Solutions Architect',
  'Technical Architect',
  'Software Architect',
  'Platform Engineer',
  'Infrastructure Engineer',
  'Embedded Systems Engineer',
  'Firmware Engineer',
  'Game Developer',
  'Graphics Engineer',
  'AR/VR Engineer',
  'Blockchain Developer',
  'Smart Contract Developer',
  'Machine Learning Engineer',
  'AI Engineer',
  'Computer Vision Engineer',
  'NLP Engineer',
  'Robotics Engineer',
  
  // Data & Analytics
  'Data Scientist',
  'Data Analyst',
  'Data Engineer',
  'Business Intelligence Analyst',
  'Analytics Engineer',
  'Quantitative Analyst',
  'Applied Scientist',
  'Statistician',
  'Operations Research Analyst',
  'Data Architect',
  'Big Data Engineer',
  'ETL Developer',
  
  // Product Management
  'Product Manager',
  'Technical Product Manager',
  'Product Owner',
  'Product Analyst',
  'Product Operations Manager',
  'Growth Product Manager',
  'Platform Product Manager',
  'Product Marketing Manager',
  'Associate Product Manager',
  
  // Design
  'UX Designer',
  'UI Designer',
  'Product Designer',
  'Graphic Designer',
  'Visual Designer',
  'Interaction Designer',
  'UX Researcher',
  'Design Systems Designer',
  'Motion Designer',
  'Brand Designer',
  'Creative Director',
  'Art Director',
  'Illustrator',
  '3D Designer',
  'Game Designer',
  
  // Marketing & Growth
  'Marketing Manager',
  'Digital Marketing Manager',
  'Content Marketing Manager',
  'Growth Marketing Manager',
  'Performance Marketing Manager',
  'Email Marketing Manager',
  'Social Media Manager',
  'SEO Specialist',
  'SEM Specialist',
  'Marketing Analyst',
  'Brand Manager',
  'Communications Manager',
  'Public Relations Manager',
  'Content Strategist',
  'Copywriter',
  'Technical Writer',
  'Content Creator',
  
  // Sales & Business Development
  'Account Executive',
  'Sales Development Representative',
  'Business Development Representative',
  'Sales Manager',
  'Account Manager',
  'Customer Success Manager',
  'Solutions Engineer',
  'Sales Engineer',
  'Channel Partner Manager',
  'Regional Sales Manager',
  'Enterprise Account Executive',
  'Inside Sales Representative',
  
  // Customer Success & Support
  'Customer Support Specialist',
  'Technical Support Engineer',
  'Customer Success Specialist',
  'Customer Experience Manager',
  'Support Engineer',
  'Implementation Specialist',
  'Onboarding Specialist',
  'Community Manager',
  
  // Operations & Strategy
  'Operations Manager',
  'Business Operations Manager',
  'Strategy Manager',
  'Management Consultant',
  'Business Analyst',
  'Operations Analyst',
  'Supply Chain Manager',
  'Logistics Manager',
  'Project Manager',
  'Program Manager',
  'Scrum Master',
  'Agile Coach',
  'Quality Assurance Manager',
  'Six Sigma Specialist',
  
  // Finance & Accounting
  'Financial Analyst',
  'Accountant',
  'Controller',
  'Finance Manager',
  'FP&A Analyst',
  'Investment Analyst',
  'Treasury Analyst',
  'Tax Analyst',
  'Audit Associate',
  'Risk Analyst',
  'Credit Analyst',
  'Pricing Analyst',
  'Revenue Operations Analyst',
  
  // Human Resources
  'Recruiter',
  'Technical Recruiter',
  'HR Manager',
  'HR Business Partner',
  'Talent Acquisition Manager',
  'People Operations Manager',
  'Compensation Analyst',
  'Benefits Administrator',
  'HR Generalist',
  'Organizational Development Specialist',
  'Learning & Development Manager',
  'Training Specialist',
  
  // Legal & Compliance
  'Corporate Counsel',
  'Legal Counsel',
  'Paralegal',
  'Compliance Manager',
  'Privacy Specialist',
  'Contract Manager',
  'IP Specialist',
  'Regulatory Affairs Specialist',
  
  // Healthcare & Life Sciences
  'Clinical Research Associate',
  'Medical Science Liaison',
  'Regulatory Affairs Manager',
  'Clinical Trial Manager',
  'Biostatistician',
  'Bioinformatics Scientist',
  'Research Associate',
  'Laboratory Technician',
  'Pharmaceutical Scientist',
  'Medical Writer',
  'Healthcare Consultant',
  'Nurse Practitioner',
  'Physician Assistant',
  'Medical Doctor',
  'Pharmacist',
  'Clinical Pharmacist',
  
  // Engineering (Non-Software)
  'Mechanical Engineer',
  'Electrical Engineer',
  'Civil Engineer',
  'Chemical Engineer',
  'Aerospace Engineer',
  'Biomedical Engineer',
  'Industrial Engineer',
  'Manufacturing Engineer',
  'Materials Engineer',
  'Environmental Engineer',
  'Structural Engineer',
  'Hardware Engineer',
  'Process Engineer',
  'Quality Engineer',
  'Reliability Engineer',
  'HVAC Engineer',
  'Controls Engineer',
  'Instrumentation Engineer',
  'Validation Engineer',
  
  // Research & Science
  'Research Scientist',
  'Scientist',
  'Chemist',
  'Biologist',
  'Physicist',
  'Materials Scientist',
  'Environmental Scientist',
  'Geologist',
  'Microbiologist',
  'Biochemist',
  'Molecular Biologist',
  
  // Supply Chain & Procurement
  'Supply Chain Analyst',
  'Procurement Specialist',
  'Buyer',
  'Sourcing Manager',
  'Inventory Manager',
  'Warehouse Manager',
  'Transportation Manager',
  'Demand Planner',
  'Supply Planner',
  
  // Real Estate & Construction
  'Real Estate Analyst',
  'Property Manager',
  'Construction Manager',
  'Project Engineer',
  'Estimator',
  'Architect',
  'Urban Planner',
  'Facilities Manager',
  
  // Media & Entertainment
  'Video Editor',
  'Producer',
  'Editor',
  'Journalist',
  'Content Producer',
  'Broadcast Engineer',
  'Audio Engineer',
  'Sound Designer',
  'Cinematographer',
  'Photographer',
  
  // Trades & Skilled Labor
  'Electrician',
  'Plumber',
  'HVAC Technician',
  'Maintenance Technician',
  'Field Service Technician',
  'Installation Technician',
  'Calibration Technician',
  
  // Education & Training
  'Instructional Designer',
  'Curriculum Developer',
  'Education Specialist',
  'Teacher',
  'Professor',
  'Tutor',
  'Corporate Trainer',
  
  // Additional Specialized Roles
  'UX Writer',
  'Localization Specialist',
  'Translation Specialist',
  'Event Planner',
  'Sustainability Manager',
  'ESG Analyst',
  'Grant Writer',
  'Fundraising Manager',
  'Chief of Staff',
  'Executive Assistant',
  'Office Manager',
  'Administrative Assistant',
  'Receptionist',
];

export const LOCATIONS = [
  // Major US Tech Hubs
  'San Francisco, CA',
  'New York, NY',
  'Seattle, WA',
  'Austin, TX',
  'Boston, MA',
  'Los Angeles, CA',
  'Chicago, IL',
  'Denver, CO',
  'Atlanta, GA',
  'Washington, DC',
  'San Diego, CA',
  'Portland, OR',
  'Dallas, TX',
  'Miami, FL',
  'Phoenix, AZ',
  'Philadelphia, PA',
  'Houston, TX',
  'San Jose, CA',
  'Palo Alto, CA',
  'Mountain View, CA',
  'Sunnyvale, CA',
  'Redwood City, CA',
  'Oakland, CA',
  'Berkeley, CA',
  'Santa Monica, CA',
  'Irvine, CA',
  'Boulder, CO',
  'Cambridge, MA',
  'Raleigh, NC',
  'Durham, NC',
  'Charlotte, NC',
  'Nashville, TN',
  'Salt Lake City, UT',
  'Minneapolis, MN',
  'Pittsburgh, PA',
  'Detroit, MI',
  'Columbus, OH',
  'Indianapolis, IN',
  'Milwaukee, WI',
  'Kansas City, MO',
  'St. Louis, MO',
  'Las Vegas, NV',
  'Omaha, NE',
  'Birmingham, AL',
  
  // State-level
  'California',
  'New York',
  'Texas',
  'Florida',
  'Washington',
  'Massachusetts',
  'Illinois',
  'Colorado',
  'Georgia',
  'North Carolina',
  'Virginia',
  'Oregon',
  'Arizona',
  'Pennsylvania',
  'Ohio',
  'Michigan',
  'Utah',
  'Tennessee',
  
  // Regions
  'Remote',
  'Anywhere in US',
  'East Coast',
  'West Coast',
  'Midwest',
  'South',
  'Northeast',
  'Southwest',
  'Pacific Northwest',
  'Bay Area',
  'Silicon Valley',
  'Greater Boston',
  'Greater Los Angeles',
  'Greater New York',
  'Tri-State Area',
  'Research Triangle',
  
  // International (common for US companies)
  'Toronto, Canada',
  'Vancouver, Canada',
  'London, UK',
  'Berlin, Germany',
  'Amsterdam, Netherlands',
  'Paris, France',
  'Dublin, Ireland',
  'Singapore',
  'Sydney, Australia',
  'Tokyo, Japan',
  'Hong Kong',
  'Bangalore, India',
  'Tel Aviv, Israel',
  'Mexico City, Mexico',
];
